apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: kirk-gpt-inference-stub
  namespace: kirk-gpt

  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: kirk-gpt-inference-stub

  namespaceSelector:
    matchNames:
      - kirk-gpt

  endpoints:
    - port: http
      path: /metrics
      interval: 5s
      scrapeTimeout: 3s