apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: kirk-gpt-models
  namespace: kirk-gpt

spec:
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 5Gi

  storageClassName:
    YOUR_SHARED_STORAGE_CLASS