apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: ec-pro-models
  namespace: ec-pro

spec:
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 5Gi

  storageClassName:
    YOUR_SHARED_STORAGE_CLASS