apiVersion: monitoring.coreos.com/v1

kind: ServiceMonitor

metadata:
  name: kirk-gpt-inference
  namespace: kirk-gpt

  labels:
    app: kirk-gpt-inference


spec:
  selector:
    matchLabels:
      app: kirk-gpt-inference

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s